import { Newspaper, TVChannel, Quote, AIModel } from './types';

export const MOTIVATIONAL_QUOTES: Quote[] = [
  { text: "সাফল্য কোনো গন্তব্য নয়, এটি একটি নিরন্তর যাত্রা। পথের প্রতিটি পদক্ষেপই আপনাকে নতুন শিক্ষা দেয়।" },
  { text: "ধৈর্য ধরুন, কারণ প্রত্যেক কঠিন সময়ের পরেই আসে সহজ সময়। মহান আল্লাহ উত্তম পরিকল্পনাকারী।" },
  { text: "জ্ঞান অর্জনের কোনো নির্দিষ্ট বয়স নেই, দোলনা থেকে কবর পর্যন্ত জ্ঞান অন্বেষণ করুন।" },
  { text: "আপনার আজকের পরিশ্রমই আগামীকালের সাফল্যের চাবিকাঠি। স্বপ্ন দেখুন এবং তা পূরণে কাজ করুন।" },
  { text: "সময় এবং স্রোত কারো জন্য অপেক্ষা করে না, তাই প্রতিটি মুহূর্তকে কাজে লাগান।" },
  { text: "যে নিজেকে চিনতে পেরেছে, সে-ই তার রবকে চিনতে পেরেছে। আত্মশুদ্ধিই প্রকৃত সফলতা।" },
  { text: "হতাশ হবেন না, কারণ জীবনের প্রতিটি সূর্যাস্তই একটি নতুন সূর্যোদয়ের প্রতিশ্রুতি নিয়ে আসে।" },
  { text: "বড় কিছু অর্জন করতে হলে ছোট ছোট পদক্ষেপ নিতে ভয় পাবেন না। হাজার মাইলের যাত্রা একটি পদক্ষেপ দিয়েই শুরু হয়।" },
  { text: "শিক্ষার শেকড় তেতো হলেও এর ফল অনেক মিষ্টি। জ্ঞানই একমাত্র সম্পদ যা কেউ কেড়ে নিতে পারে না।" },
  { text: "ব্যর্থতা মানে হেরে যাওয়া নয়, বরং নতুন করে শুরু করার সুযোগ। দ্বিগুণ উৎসাহে এগিয়ে যান।" },
  { text: "সততা এবং সত্যবাদিতা মানুষের জীবনের সবচেয়ে বড় অলংকার। সত্যের পথে অবিচল থাকুন।" },
  { text: "অন্যের ভুল থেকে শিক্ষা নিন, কারণ নিজের সব ভুল করে শেখার জন্য জীবন খুব ছোট।" },
  { text: "কৃতজ্ঞতা প্রকাশ করুন, আপনার জীবন প্রশান্তিতে ভরে উঠবে। যা পেয়েছেন তার কদর করুন।" },
  { text: "বই হচ্ছে এমন এক বন্ধু যা আপনাকে কখনো প্রতারিত করবে না। পড়ার অভ্যাস গড়ে তুলুন।" },
  { text: "নেতিবাচক চিন্তা থেকে দূরে থাকুন, ইতিবাচক মনোভাব আপনার জীবন বদলে দেবে।" },
];

export const BANGLA_NEWSPAPERS: Newspaper[] = [
  // Bangladesh
  { name: "দৈনিক আমার দেশ", url: "https://www.dailyamardesh.com/", category: 'bangla' },
  { name: "দৈনিক ইনকিলাব", url: "https://dailyinqilab.com", category: 'bangla' },
  { name: "দৈনিক নয়াদিগন্ত", url: "https://www.dailynayadiganta.com", category: 'bangla' },
  { name: "দৈনিক বাংলাদেশ প্রতিদিন", url: "https://www.bd-pratidin.com", category: 'bangla' },
  { name: "দৈনিক ইত্তেফাক", url: "https://www.ittefaq.com.bd", category: 'bangla' },
  { name: "দৈনিক জুগান্তর", url: "https://www.jugantor.com", category: 'bangla' },
  { name: "দৈনিক কালের কণ্ঠ", url: "https://www.kalerkantho.com", category: 'bangla' },
  { name: "দৈনিক প্রথম আলো", url: "https://www.prothomalo.com", category: 'bangla' },
  { name: "দৈনিক মানবজমিন", url: "https://mzamin.com", category: 'bangla' },
  { name: "দৈনিক সমকাল", url: "https://samakal.com", category: 'bangla' },
  { name: "দৈনিক কালবেলা", url: "https://www.kalbela.com", category: 'bangla' },
  { name: "দৈনিক বণিক বার্তা", url: "https://www.bonikbarta.com", category: 'bangla' },
  { name: "দৈনিক জয়জয়দিন", url: "https://www.jaijaidinbd.com", category: 'bangla' },
  { name: "দৈনিক আমাদের সময়", url: "https://www.dainikamadershomoy.com", category: 'bangla' },
  { name: "দৈনিক জনকণ্ঠ", url: "https://www.dailyjanakantha.com", category: 'bangla' },
  { name: "দৈনিক সংবাদ", url: "https://sangbad.net.bd", category: 'bangla' },
  { name: "দৈনিক মানবকণ্ঠ", url: "https://www.manobkantha.com.bd", category: 'bangla' },
  { name: "দৈনিক আজকালের খবর", url: "https://www.ajkalerkhobor.net", category: 'bangla' },
  { name: "দৈনিক আজকের পত্রিকা", url: "https://www.ajkerpatrika.com", category: 'bangla' },
  { name: "দৈনিক প্রতিদিনের সংবাদ", url: "https://www.protidinersangbad.com", category: 'bangla' },
  { name: "দৈনিক বাংলাদেশের খবর", url: "https://www.bangladesherkhabor.net", category: 'bangla' },
  { name: "দৈনিক প্রতিদিনের বাংলাদেশ", url: "https://protidinerbangladesh.com", category: 'bangla' },
  { name: "দৈনিক বাংলাদেশ জার্নাল", url: "https://www.bd-journal.com", category: 'bangla' },
  { name: "দৈনিক আমার সংবাদ", url: "https://www.amarsangbad.com", category: 'bangla' },
  { name: "দৈনিক ভোরের পাতা", url: "https://www.dailyvorerpata.com", category: 'bangla' },
  { name: "দৈনিক সংগ্রাম", url: "https://dailysangram.com", category: 'bangla' },
  { name: "দৈনিক দেশ রূপান্তর", url: "https://deshrupantor.com", category: 'bangla' },
  { name: "দৈনিক আলোকিত বাংলাদেশ", url: "https://www.alokitobangladesh.com", category: 'bangla' },
  { name: "দৈনিক ভোরের কাগজ", url: "https://www.bhorerkagoj.com", category: 'bangla' },
  { name: "দৈনিক পট্রিকা", url: "https://www.potrika.com", category: 'bangla' },
  { name: "দৈনিক সকাল", url: "https://www.dainiksokal.com", category: 'bangla' },
  { name: "দৈনিক গণকণ্ঠ", url: "https://www.gonokontho.com.bd", category: 'bangla' },
  { name: "দৈনিক দিব্যজ্যোতি", url: "https://www.divyajoti.com", category: 'bangla' },
  { name: "দৈনিক সন্ধ্যা", url: "https://www.dainiksandhya.com", category: 'bangla' },
  { name: "দৈনিক অধিকার", url: "https://www.adhikar.news", category: 'bangla' },
  { name: "দৈনিক দৈনিক সংবাদ", url: "https://www.dainiksangbad.com", category: 'bangla' },
  { name: "দৈনিক প্রথমা", url: "https://www.prathoma.com", category: 'bangla' },
  { name: "দৈনিক সূর্য", url: "https://www.surypatrika.com", category: 'bangla' },
  { name: "দৈনিক দৈনিক হিউম", url: "https://www.dainikhum.com", category: 'bangla' },
  { name: "দৈনিক নতুন দিন", url: "https://www.natundin.com", category: 'bangla' },
  
  // India (West Bengal & Others)
  { name: "আনন্দবাজার পত্রিকা", url: "https://anandabazar.com", category: 'bangla', region: 'India' },
  { name: "বর্তমান", url: "https://bartamanpatrika.com", category: 'bangla', region: 'India' },
  { name: "আজকাল", url: "https://aajkaal.in", category: 'bangla', region: 'India' },
  { name: "সংবাদ প্রতিদিন", url: "https://sangbadpratidin.in", category: 'bangla', region: 'India' },
  { name: "এই সময়", url: "https://eisamay.com", category: 'bangla', region: 'India' },
  { name: "এবেলা", url: "https://ebela.in", category: 'bangla', region: 'India' },
  { name: "গণশক্তি", url: "https://ganashakti.com", category: 'bangla', region: 'India' },
  { name: "উত্তরবঙ্গ সংবাদ", url: "https://uttarbangasambad.com", category: 'bangla', region: 'India' },
  { name: "দৈনিক সংবাদ (ত্রিপুরা)", url: "https://dainiksambad.net", category: 'bangla', region: 'India' },
  { name: "আসামিয়া প্রতিদিন", url: "https://asamiapratidin.co.in", category: 'bangla', region: 'India' },
];

export const INTL_NEWSPAPERS: Newspaper[] = [
  // USA
  { name: "The New York Times", url: "https://www.nytimes.com", category: 'intl', region: "USA" },
  { name: "The Washington Post", url: "https://www.washingtonpost.com", category: 'intl', region: "USA" },
  { name: "The Wall Street Journal", url: "https://www.wsj.com", category: 'intl', region: "USA" },
  { name: "Los Angeles Times", url: "https://www.latimes.com", category: 'intl', region: "USA" },
  { name: "Chicago Tribune", url: "https://www.chicagotribune.com", category: 'intl', region: "USA" },
  { name: "The Boston Globe", url: "https://www.bostonglobe.com", category: 'intl', region: "USA" },
  { name: "USA Today", url: "https://www.usatoday.com", category: 'intl', region: "USA" },
  { name: "New York Daily News", url: "https://www.nydailynews.com", category: 'intl', region: "USA" },
  { name: "Newsday", url: "https://www.newsday.com", category: 'intl', region: "USA" },
  { name: "The Dallas Morning News", url: "https://www.dallasnews.com", category: 'intl', region: "USA" },
  { name: "Houston Chronicle", url: "https://www.houstonchronicle.com", category: 'intl', region: "USA" },
  { name: "The Denver Post", url: "https://www.denverpost.com", category: 'intl', region: "USA" },
  { name: "San Francisco Chronicle", url: "https://www.sfchronicle.com", category: 'intl', region: "USA" },
  { name: "The Seattle Times", url: "https://www.seattletimes.com", category: 'intl', region: "USA" },
  { name: "The Arizona Republic", url: "https://www.azcentral.com", category: 'intl', region: "USA" },
  { name: "Miami Herald", url: "https://www.miamiherald.com", category: 'intl', region: "USA" },
  { name: "The Atlanta Journal-Constitution", url: "https://www.ajc.com", category: 'intl', region: "USA" },
  { name: "The Baltimore Sun", url: "https://www.baltimoresun.com", category: 'intl', region: "USA" },
  { name: "The Charlotte Observer", url: "https://www.charlotteobserver.com", category: 'intl', region: "USA" },
  { name: "The Plain Dealer", url: "https://www.cleveland.com", category: 'intl', region: "USA" },
  { name: "The Detroit News", url: "https://www.detroitnews.com", category: 'intl', region: "USA" },
  { name: "Detroit Free Press", url: "https://www.freep.com", category: 'intl', region: "USA" },
  { name: "The Indianapolis Star", url: "https://www.indystar.com", category: 'intl', region: "USA" },
  { name: "Milwaukee Journal Sentinel", url: "https://www.jsonline.com", category: 'intl', region: "USA" },
  { name: "The Oregonian", url: "https://www.oregonlive.com", category: 'intl', region: "USA" },
  { name: "The Philadelphia Inquirer", url: "https://www.philly.com", category: 'intl', region: "USA" },
  { name: "Pittsburgh Post-Gazette", url: "https://www.post-gazette.com", category: 'intl', region: "USA" },
  { name: "St. Louis Post-Dispatch", url: "https://www.stltoday.com", category: 'intl', region: "USA" },
  { name: "Tampa Bay Times", url: "https://www.tampabay.com", category: 'intl', region: "USA" },
  { name: "The Mercury News", url: "https://www.mercurynews.com", category: 'intl', region: "USA" },
  { name: "Orange County Register", url: "https://www.ocregister.com", category: 'intl', region: "USA" },
  { name: "The San Diego Union-Tribune", url: "https://www.sandiegouniontribune.com", category: 'intl', region: "USA" },
  
  // UK & Europe
  { name: "The Daily Telegraph", url: "https://www.telegraph.co.uk", category: 'intl', region: "UK" },
  { name: "Daily Mail", url: "https://www.dailymail.co.uk", category: 'intl', region: "UK" },
  { name: "Daily Mirror", url: "https://www.mirror.co.uk", category: 'intl', region: "UK" },
  { name: "Daily Express", url: "https://www.express.co.uk", category: 'intl', region: "UK" },
  { name: "The Sun", url: "https://www.thesun.co.uk", category: 'intl', region: "UK" },
  { name: "The Independent", url: "https://www.independent.co.uk", category: 'intl', region: "UK" },
  { name: "Financial Times", url: "https://www.ft.com", category: 'intl', region: "UK" },
  { name: "The Economist", url: "https://www.economist.com", category: 'intl', region: "UK" },
  { name: "BBC News", url: "https://www.bbc.com", category: 'intl', region: "UK" },
  { name: "Reuters", url: "https://www.reuters.com", category: 'intl', region: "UK" },
  { name: "France 24", url: "https://www.france24.com", category: 'intl', region: "France" },
  { name: "Deutsche Welle", url: "https://www.dw.com", category: 'intl', region: "Germany" },
  { name: "RT", url: "https://www.rt.com", category: 'intl', region: "Russia" },

  // Canada & ANZ
  { name: "The Globe and Mail", url: "https://www.theglobeandmail.com", category: 'intl', region: "Canada" },
  { name: "Toronto Star", url: "https://www.thestar.com", category: 'intl', region: "Canada" },
  { name: "The Sydney Morning Herald", url: "https://www.smh.com.au", category: 'intl', region: "Australia" },
  { name: "The Age", url: "https://www.theage.com.au", category: 'intl', region: "Australia" },
  { name: "New Zealand Herald", url: "https://www.nzherald.co.nz", category: 'intl', region: "NZ" },
  { name: "Stuff.co.nz", url: "https://www.stuff.co.nz", category: 'intl', region: "NZ" },

  // News Agencies / Networks / Magazines
  { name: "Associated Press", url: "https://www.ap.org", category: 'intl', region: "USA" },
  { name: "Bloomberg", url: "https://www.bloomberg.com", category: 'intl', region: "USA" },
  { name: "Forbes", url: "https://www.forbes.com", category: 'intl', region: "USA" },
  { name: "CNBC", url: "https://www.cnbc.com", category: 'intl', region: "USA" },
  { name: "CNN", url: "https://www.cnn.com", category: 'intl', region: "USA" },
  { name: "Fox News", url: "https://www.foxnews.com", category: 'intl', region: "USA" },
  { name: "NBC News", url: "https://www.nbcnews.com", category: 'intl', region: "USA" },
  { name: "ABC News", url: "https://www.abcnews.go.com", category: 'intl', region: "USA" },
  { name: "CBS News", url: "https://www.cbsnews.com", category: 'intl', region: "USA" },
  { name: "MSNBC", url: "https://www.msnbc.com", category: 'intl', region: "USA" },
  { name: "U.S. News & World Report", url: "https://www.usnews.com", category: 'intl', region: "USA" },
  { name: "The Atlantic", url: "https://www.theatlantic.com", category: 'intl', region: "USA" },
  { name: "The New Yorker", url: "https://www.newyorker.com", category: 'intl', region: "USA" },
  { name: "Harper's Magazine", url: "https://www.harpers.org", category: 'intl', region: "USA" },
  { name: "The Nation", url: "https://www.thenation.com", category: 'intl', region: "USA" },
  { name: "National Review", url: "https://www.nationalreview.com", category: 'intl', region: "USA" },
  { name: "The American Conservative", url: "https://www.theamericanconservative.com", category: 'intl', region: "USA" },
  { name: "Jacobin", url: "https://www.jacobinmag.com", category: 'intl', region: "USA" },
  { name: "The Intercept", url: "https://www.theintercept.com", category: 'intl', region: "USA" },
  { name: "ProPublica", url: "https://www.propublica.org", category: 'intl', region: "USA" },
  { name: "BuzzFeed News", url: "https://www.buzzfeednews.com", category: 'intl', region: "USA" },
  { name: "Vice News", url: "https://www.vice.com", category: 'intl', region: "USA" },
  { name: "HuffPost", url: "https://www.huffpost.com", category: 'intl', region: "USA" },
  { name: "Politico", url: "https://www.politico.com", category: 'intl', region: "USA" },
  { name: "The Hill", url: "https://www.thehill.com", category: 'intl', region: "USA" },
  { name: "Roll Call", url: "https://www.rollcall.com", category: 'intl', region: "USA" },
  { name: "National Journal", url: "https://www.nationaljournal.com", category: 'intl', region: "USA" },
  { name: "CQ Roll Call", url: "https://www.cqrollcall.com", category: 'intl', region: "USA" },

  // Asia (English)
  { name: "Al Jazeera", url: "https://www.aljazeera.com", category: 'intl', region: "Qatar" },
  { name: "South China Morning Post", url: "https://www.scmp.com", category: 'intl', region: "Hong Kong" },
  { name: "The Japan Times", url: "https://www.japantimes.co.jp", category: 'intl', region: "Japan" },
  { name: "The Korea Times", url: "https://www.koreatimes.co.kr", category: 'intl', region: "South Korea" },
  { name: "The Straits Times", url: "https://www.straitstimes.com", category: 'intl', region: "Singapore" },
  { name: "The Hindu", url: "https://www.thehindu.com", category: 'intl', region: "India" },
  { name: "The Times of India", url: "https://timesofindia.indiatimes.com", category: 'intl', region: "India" },
  { name: "Hindustan Times", url: "https://www.hindustantimes.com", category: 'intl', region: "India" },
  { name: "The Indian Express", url: "https://www.indianexpress.com", category: 'intl', region: "India" },
  { name: "The Hans India", url: "https://www.thehansindia.com", category: 'intl', region: "India" },
  { name: "Deccan Chronicle", url: "https://www.deccanchronicle.com", category: 'intl', region: "India" },
  { name: "The Statesman", url: "https://www.thestatesman.com", category: 'intl', region: "India" },
  { name: "The Telegraph", url: "https://www.telegraphindia.com", category: 'intl', region: "India" },
  { name: "The Tribune", url: "https://www.tribuneindia.com", category: 'intl', region: "India" },
  { name: "The Pioneer", url: "https://www.dailypioneer.com", category: 'intl', region: "India" },
  { name: "The Asian Age", url: "https://www.asianage.com", category: 'intl', region: "India" },
  { name: "Business Standard", url: "https://www.business-standard.com", category: 'intl', region: "India" },
  { name: "The Financial Express", url: "https://www.financialexpress.com", category: 'intl', region: "India" },
  { name: "Moneycontrol", url: "https://www.moneycontrol.com", category: 'intl', region: "India" },
  { name: "Mint", url: "https://www.livemint.com", category: 'intl', region: "India" },
  { name: "The Economic Times", url: "https://www.economictimes.indiatimes.com", category: 'intl', region: "India" },
  { name: "DNA India", url: "https://www.dnaindia.com", category: 'intl', region: "India" },
  { name: "Mid-Day", url: "https://www.mid-day.com", category: 'intl', region: "India" },
  { name: "Afternoon Voice", url: "https://www.afternoonvoice.com", category: 'intl', region: "India" },
  { name: "Sakal Times", url: "https://www.sakaltimes.com", category: 'intl', region: "India" },
  { name: "Lokmat", url: "https://www.lokmat.com", category: 'intl', region: "India" },
  { name: "Pudhari", url: "https://www.pudhari.news", category: 'intl', region: "India" },
  { name: "Tarun Bharat", url: "https://www.tarunbharat.com", category: 'intl', region: "India" },
  { name: "Maharashtra Times", url: "https://www.maharashtratimes.com", category: 'intl', region: "India" },
  { name: "Loksatta", url: "https://www.loksatta.com", category: 'intl', region: "India" },
  { name: "Samayam", url: "https://www.samayam.com", category: 'intl', region: "India" },
  { name: "Vijay Karnataka", url: "https://www.vijaykarnataka.com", category: 'intl', region: "India" },
  { name: "Andhra Jyothy", url: "https://www.andhrajyothy.com", category: 'intl', region: "India" },
  { name: "Eenadu", url: "https://www.eenadu.net", category: 'intl', region: "India" },
  { name: "Sakshi", url: "https://www.sakshi.com", category: 'intl', region: "India" },
  { name: "Andhra Bhoomi", url: "https://www.andhrabhoomi.net", category: 'intl', region: "India" },
  { name: "Vaartha", url: "https://www.vaartha.com", category: 'intl', region: "India" },
  { name: "Andhra Prabha", url: "https://www.andhraprabha.com", category: 'intl', region: "India" },
  { name: "Prajasakti", url: "https://www.prajasakti.com", category: 'intl', region: "India" },
  { name: "Mana Telangana", url: "https://www.manatelangana.com", category: 'intl', region: "India" },
  { name: "Namasthe Telangana", url: "https://www.namasthetelangana.com", category: 'intl', region: "India" },
  { name: "Andhra Wishesh", url: "https://www.andhrawishesh.com", category: 'intl', region: "India" },
  { name: "Greatandhra", url: "https://www.greatandhra.com", category: 'intl', region: "India" },
  { name: "AP Herald", url: "https://www.apherald.com", category: 'intl', region: "India" },
  { name: "Telugu Post", url: "https://www.telugupost.com", category: 'intl', region: "India" },
];

export const ARAB_NEWSPAPERS: Newspaper[] = [
  { name: "الجزيرة (Al Jazeera)", url: "https://www.aljazeera.net/", category: 'arab' },
  { name: "الشرق الأوسط (Asharq Al-Awsat)", url: "https://aawsat.com/", category: 'arab' },
  { name: "الأهرام (Al-Ahram)", url: "https://ahram.org.eg/", category: 'arab' },
  { name: "العربية (Al Arabiya)", url: "https://www.alarabiya.net/", category: 'arab' },
  { name: "الاتحاد (Al-Ittihad)", url: "https://www.alittihad.ae/", category: 'arab' },
  { name: "الاقتصادية (Al-Eqtisadiah)", url: "https://www.aleqt.com/", category: 'arab' },
  { name: "المصري اليوم (Al-Masry Al-Youm)", url: "https://www.almasryalyoum.com/", category: 'arab' },
  { name: "اليوم السابع (Youm7)", url: "https://www.youm7.com/", category: 'arab' },
  { name: "أخبارنا (Akhbarona)", url: "https://www.akhbarona.com/", category: 'arab' },
  { name: "سبق (Sabq)", url: "https://www.sabq.org/", category: 'arab' },
  { name: "الرياض (Al-Riyadh)", url: "https://www.alriyadh.com/", category: 'arab' },
  { name: "عكاظ (Okaz)", url: "https://www.okaz.com.sa/", category: 'arab' },
  { name: "الوطن (Al-Watan)", url: "https://www.alwatan.com.sa/", category: 'arab' },
  { name: "اليوم (Al-Yaum)", url: "https://www.alyaum.com/", category: 'arab' },
  { name: "الجريدة (Al-Jarida)", url: "https://www.aljarida.com/", category: 'arab' },
  { name: "القبس (Al-Qabas)", url: "https://www.alqabas.com/", category: 'arab' },
  { name: "الأنباء (Al-Anba)", url: "https://www.alanba.com.kw/", category: 'arab' },
  { name: "الرأي (Al-Rai)", url: "https://www.alrai.com/", category: 'arab' },
  { name: "الدستور (Al-Dustour)", url: "https://www.addustour.com/", category: 'arab' },
  { name: "الغد (Al-Ghad)", url: "https://www.alghad.tv/", category: 'arab' },
  { name: "الصباح (Assabah)", url: "https://www.assabah.news.tn/", category: 'arab' },
  { name: "أخبارك (Akhbarak)", url: "https://www.akhbarak.net/", category: 'arab' },
  { name: "هسبريس (Hespress)", url: "https://www.hespress.com/", category: 'arab' },
  { name: "المدينة (Al-Madina)", url: "https://www.almadenahnews.com/", category: 'arab' },
  { name: "الشرق (Al-Sharq)", url: "https://www.alsharq.net.sa/", category: 'arab' },
  { name: "الوفد (Al-Wafd)", url: "https://www.alwafd.news/", category: 'arab' },
  { name: "صوت الأمة (Sout Al-Omma)", url: "https://www.soutalomma.com/", category: 'arab' },
  { name: "فيتو (Veto)", url: "https://www.vetogate.com/", category: 'arab' },
  { name: "الدستور (Al-Dostor)", url: "https://www.dostor.org/", category: 'arab' },
  { name: "البوابة (Al-Bawaba)", url: "https://www.albawaba.com/", category: 'arab' },
  { name: "مصراوي (Masrawy)", url: "https://www.masrawy.com/", category: 'arab' },
  { name: "الفجر (Al-Fagr)", url: "https://www.elfagr.org/", category: 'arab' },
  { name: "صدى البلد (Sada Elbalad)", url: "https://www.sadaelbalad.com/", category: 'arab' },
  { name: "الشروق (Al-Shorouk)", url: "https://www.shorouknews.com/", category: 'arab' },
  { name: "البوابة نيوز (Al-Bawabh News)", url: "https://www.albawabhnews.com/", category: 'arab' },
  { name: "الفن (El-Fann)", url: "https://www.elfann.com/", category: 'arab' },
  { name: "الأهرام (Al-Ahram)", url: "https://www.alahram.org.eg/", category: 'arab' },
  { name: "أخبار اليوم (Akhbar Al-Youm)", url: "https://www.akhbarelyom.com/", category: 'arab' },
];

export const ISLAMIC_CONTENT: Newspaper[] = [
  // Preserving first 14 items (0-13)
  { name: "মাসিক আলকাউসার", url: "https://www.alkawsar.com/bn/", category: 'islamic' },
  { name: "মাসিক আদর্শ নারী", url: "https://adarshanari.com/", category: 'islamic' },
  { name: "মাসিক রহমত", url: "http://www.monthlyrahmat.blogspot.com/", category: 'islamic' },
  { name: "মাসিক দাওয়াতুল হক", url: "https://www.dawatulhaq.com/", category: 'islamic' },
  { name: "মুসলিম বাংলা", url: "https://muslimbangla.com/", category: 'islamic' },
  { name: "কুরআনের জ্যোতি", url: "http://quranerjyoti.com/", category: 'islamic' },
  { name: "বাংলা হাদিস", url: "https://www.hadithbd.com/", category: 'islamic' },
  { name: "আই-অনলাইন মিডিয়া", url: "http://i-onlinemedia.net/", category: 'islamic' },
  { name: "ইসলাম হাউস", url: "https://islamhouse.com/bn", category: 'islamic' },
  { name: "ইসলাম কিউএ", url: "https://islamqa.info/bn", category: 'islamic' },
  { name: "দাওয়াহ ইলাল্লাহ", url: "https://dawahilallah.com/", category: 'islamic' },
  { name: "ইসলামিক বিডি", url: "https://islamicbd.com/", category: 'islamic' },
  { name: "কুরআন মাজিদ", url: "https://quran.gov.bd/", category: 'islamic' },
  { name: "হাদিস বিডি", url: "https://hadithbd.com/", category: 'islamic' },
  
  // New Added Links
  { name: "Fateh 24", url: "https://fateh24.com/", category: 'islamic' },
  { name: "Ask Ummah", url: "https://www.askummah.com/", category: 'islamic' },
  { name: "iFatwa", url: "https://ifatwa.info/", category: 'islamic' },
  { name: "Islam QA (English)", url: "https://islamqa.info/en", category: 'islamic' },
  { name: "Islam Web", url: "https://www.islamweb.net/en/", category: 'islamic' },
  { name: "Sunnah", url: "https://sunnah.com/", category: 'islamic' },
  { name: "Quran.com", url: "http://quran.com/", category: 'islamic' },
  { name: "Response to Anti-Islam", url: "http://www.response-to-anti-islam.com/", category: 'islamic' },
  { name: "Raindrops Media", url: "https://raindrops.media/", category: 'islamic' },
  { name: "UVBD TV", url: "http://www.uvbd.tv/", category: 'islamic' },
  { name: "As-Sunnah Trust", url: "http://assunnahtrust.com/", category: 'islamic' },
  { name: "Darul Ilm", url: "http://darulilm.org/", category: 'islamic' },
  { name: "Way to Jannah", url: "https://www.waytojannah.net/", category: 'islamic' },
  { name: "Abu Bakar Zakaria", url: "https://abubakarzakaria.com/", category: 'islamic' },
  { name: "Ali Hasan Osama", url: "https://alihasanosama.com/", category: 'islamic' },
  { name: "Arif Azad", url: "http://arifazad.blogspot.com/", category: 'islamic' },
  { name: "Rafan Official", url: "https://rafanofficial.wordpress.com/", category: 'islamic' },
  { name: "Islamic Astrology", url: "http://islamicastrolgy.blogspot.com/", category: 'islamic' },
];

export const TV_CHANNELS: TVChannel[] = [
  { name: "বিটিভি লাইভ", url: "https://www.btvlive.gov.bd/channel/BTV", iconClass: "fas fa-broadcast-tower", colorClass: "text-blue-600" },
  { name: "NTV লাইভ", url: "https://www.ntvbd.com/live-tv", iconClass: "fas fa-tv", colorClass: "text-red-600" },
  { name: "Somoy TV", url: "https://www.somoynews.tv/live", iconClass: "fas fa-clock", colorClass: "text-cyan-600" },
  { name: "GTV লাইভ", url: "https://www.gtvbd.tv/live", iconClass: "fas fa-satellite-dish", colorClass: "text-green-600" },
  { name: "মাছরাঙা টিভি", url: "https://maasranga.tv/live-streaming/", iconClass: "fas fa-fish", colorClass: "text-orange-500" },
  { name: "Jago BD", url: "https://www.jagobd.com", iconClass: "fas fa-video", colorClass: "text-rose-600" },
  { name: "CricBuzz", url: "https://www.cricbuzz.com/live-cricket-scores", iconClass: "fas fa-baseball-ball", colorClass: "text-emerald-700" },
];

export const EXTERNAL_AI_MODELS: AIModel[] = [
  { name: "ChatGPT", url: "https://chat.openai.com", icon: "fa-robot", color: "bg-emerald-600" },
  { name: "Gemini", url: "https://gemini.google.com", icon: "fa-star", color: "bg-blue-600" },
  { name: "Microsoft Copilot", url: "https://copilot.microsoft.com", icon: "fa-rocket", color: "bg-pink-600" },
  { name: "Claude", url: "https://claude.ai", icon: "fa-brain", color: "bg-orange-600" },
  { name: "Perplexity", url: "https://www.perplexity.ai", icon: "fa-search", color: "bg-teal-600" },
  { name: "HuggingChat", url: "https://huggingface.co/chat", icon: "fa-smile", color: "bg-yellow-500" },
  { name: "Poe", url: "https://poe.com", icon: "fa-bolt", color: "bg-purple-600" },
  { name: "DeepSeek", url: "https://chat.deepseek.com", icon: "fa-code", color: "bg-indigo-600" },
  { name: "Blackbox AI", url: "https://www.blackbox.ai", icon: "fa-box", color: "bg-gray-800" },
  { name: "Pi AI", url: "https://pi.ai/talk", icon: "fa-infinity", color: "bg-green-500" }
];